encoding: utf-8

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            fooforge
tagline:          'UTC+2 based IT Specialist and Speaker'
description:      'Mike Adolphs'
url:              http://fooforge.com

author:
  name:           'Mike Adolphs'
  url:            https://twitter.com/fooforge

paginate:         10

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/fooforge/fooforge.com

gems:
  - jekyll-sitemap
  
picture:
  source: "public/img/_original"
  output: "public/img"
  markup: "picturefill"
  presets:
    default:
      ppi: [1]
      attr:
        class: "default-img"
        itemprop: "image"
      source_large:
        media: "(min-width: 50em)"
        width: "800"
      source_medium:
        media: "(min-width: 25em)"
        width: "400"
      source_small:
        media: "(min-width: 12.5em)"
        width: "200"
      source_default:
        width: "1000"
